name: CI/CD for React and SpringBoot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build React  
  build-react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Install Node
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: |
          cd client
          npm install

      - name: Build Project
        run: |
          cd client
          CI=false npm run build

      - name: Upload React build artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: production-file
          path: ./client/build

  # Build & Test Spring Boot
  build-springboot:
    runs-on: ubuntu-latest
    needs: build-react
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make mvnw executable
        run: chmod +x rest/mvnw

      - name: Build Spring Boot project
        run: |
          cd rest
          ./mvnw clean install -DskipTests

      # Optional: Run tests or start the application if needed
      - name: Run Spring Boot app (optional)
        run: |
          cd rest
          nohup ./mvnw spring-boot:run &

  # Deploy React Build to SpringBoot
  deploy-react-build:
    runs-on: ubuntu-latest
    needs: build-react
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      
      - name: Download React build artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: production-file
          path: client/build
      
      - name: Copy React build files to Spring Boot static directory
        run: |
          cd $GITHUB_WORKSPACE
          cp -r ./client/build/* ./rest/src/main/resources/static/
